// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5EaVnkExx3YkNYVkHuUcqYQHii_Oz0EM',
    appId: '1:53905179525:web:566b47d769ed8c3574baec',
    messagingSenderId: '53905179525',
    projectId: 'sd-demo-app',
    authDomain: 'sd-demo-app.firebaseapp.com',
    storageBucket: 'sd-demo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7C-1MsaxrjO6pdKcO2xilUZLTc9tibWU',
    appId: '1:53905179525:android:7817d1afadd9bb3174baec',
    messagingSenderId: '53905179525',
    projectId: 'sd-demo-app',
    storageBucket: 'sd-demo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bnYhpbH-MwrJ7Neo1gi6u52S41q8_8U',
    appId: '1:53905179525:ios:02a94dee67be08c974baec',
    messagingSenderId: '53905179525',
    projectId: 'sd-demo-app',
    storageBucket: 'sd-demo-app.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bnYhpbH-MwrJ7Neo1gi6u52S41q8_8U',
    appId: '1:53905179525:ios:239a54545ecfecb374baec',
    messagingSenderId: '53905179525',
    projectId: 'sd-demo-app',
    storageBucket: 'sd-demo-app.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
